<a href="https://colab.research.google.com/github/shreyasmalewar/linearalgebra-colab/blob/master/Array_Index_Slice_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##Write a program to implement :
1. From List to Arrays
2. Array Indexing
3. Array Slicing
4. Array Reshaping

#From List to Arrays
In general, I recommend loading your data from le using Pandas or even NumPy functions.
This section assumes you have loaded or generated your data by other means and it is now
represented using Python lists. Let's look at converting your data in lists to NumPy arrays.

##1D List to array

In [0]:
#Create 1D array
from numpy import array
data = [16,23,45,12,89,56,46,20]
data = array(data)
print(data)
print(type(data))

[16 23 45 12 89 56 46 20]
<class 'numpy.ndarray'>


##2D List to Array

In [0]:
#Create 2D array
from numpy import array
data = [[16,23],[45,12],[89,56],[46,20]]
data = array(data)
print(data)
print(type(data))

[[16 23]
 [45 12]
 [89 56]
 [46 20]]
<class 'numpy.ndarray'>


##Array Indexing


In [0]:
#index 1D array
from numpy import array
data = [23,45,12,89,56]
#indexed array
print(data[3])
print(data[1])


89
45


In [0]:
#index 2D array
from numpy import array
data = [[16,23],[45,12],[89,56],[46,20]]
data = array(data)
print(data[0,0])
print(data[0,1])
print(data[1,1])
print(type(data))

16
23
12
<class 'numpy.ndarray'>


#Array Slicing:

Array Slicing
So far, so good; creating and indexing arrays looks familiar. Now we come to array slicing, and
this is one feature that causes problems for beginners to Python and NumPy arrays. Structures
like lists and NumPy arrays can be sliced. This means that a subsequence of the structure
can be indexed and retrieved. This is most useful in machine learning when specifying input
variables and output variables, or splitting training rows from testing rows. Slicing is specied
using the colon operator : with a from and to index before and after the column respectively.
The slice extends from the from index and ends one item before the to index.

In [0]:
from numpy import array
data = [1,4,6,1,2,3,8,9,3]
data = array(data)
print(data[:])
print(data[2:])
print(data[:3])
print(data[1:])
print(data[:6])
print(data[2:5])

[1 4 6 1 2 3 8 9 3]
[6 1 2 3 8 9 3]
[1 4 6]
[4 6 1 2 3 8 9 3]
[1 4 6 1 2 3]
[6 1 2]


In [0]:
#split input and output data
from numpy import array
# define array
data = array([[11, 22, 33],
		          [44, 55, 66],
		          [77, 88, 99]])
# separate data
X, y = data[:, :1], data[:, 1]
print(X)
print(y)

[[11]
 [44]
 [77]]
[22 55 88]


Split Train and Test Rows
It is common to split a loaded dataset into separate train and test sets. This is a splitting of
rows where some portion will be used to train the model and the remaining portion will be used
to estimate the skill of the trained model. This would involve slicing all columns by specifying :
in the second dimension index. The training dataset would be all rows from the beginning to
the split point.

In [0]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [0]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


#DATA SHAPE

In [0]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [0]:
#shape of array
from numpy import array
#define array
data=array([[1,2,3],
            [4,5,6],
            [7,8,9]])
#print shape
print(data.shape)

(3, 3)


In [0]:
#shape of array
from numpy import array
#define array
data=array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print('Rows: %d' % data.shape[0])
print('Col: %d' % data.shape[1])

Rows: 3
Col: 3


#Reshaping
It is common to need to reshape a one-dimensional array into a two-dimensional array with
one column and multiple arrays. NumPy provides the reshape() function on the NumPy array
object that can be used to reshape the data. The reshape() function takes a single argument
that species the new shape of the array. In the case of reshaping a one-dimensional array into
a two-dimensional array with one column, the tuple would be the shape of the array as the frst
dimension (data.shape[0]) and 1 for the second dimension.

## ARRAY RESHAPING 1D ARRAY TO 2D ARRAY


In [0]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


## ARRAY RESHAPING 2D ARRAY TO 3D ARRAY

In [0]:

from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)
