<a href="https://colab.research.google.com/github/shreyasmalewar/linearalgebra-colab/blob/master/Linear-Algebra-Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical 9:
##Assignment

Q1.Write a NumPy program to compute the multiplication of two given matrixes. 
A=[[1 2 3],
[4 5 6],
[7 8 9]]
B=[[1 1 1],
[2 2 2],
[3, 3, 3]]


In [0]:
from numpy import array
A = array([[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]])
B = array([[1, 1, 1],
      [2, 2, 2],
      [3, 3, 3]])
print(A)
print(B)
C = A * B
print(C)

Q2. Write a NumPy program to compute the outer product of two given vectors. 
v1=[[1, 0], [0, 1]]
v2=[[1, 2], [3, 4]]

In [0]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print(p)
print(q)
result = np.outer(p, q)
print("Outer product is:")
print(result)

Q3.Create the following rank 2 array with shape (3, 4) 
[[ 1 2 3 4] 
[ 5 6 7 8] 
[ 9 10 11 12]]
Demonstrate two ways of accessing the data in the middle row of the array.
1. Indexing with slices 
2. Only slices


In [0]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[:2, 1:3]
print(a[0, 1])
b[0, 0]=77
print(a[0, 1])

Q4. Write a NumPy program to compute the determinant of a given square array. 
[[1 0 3 5]
[3 6 7 2]
[3 2 4 1]
[1 2 0 1]]


In [0]:
import numpy as np
a = np.array([[1, 0, 3, 5], [3, 6, 7, 2], [3, 2, 4, 1], [1, 2, 0, 1]])
print("Original Array:")
print(a)
result = np.linalg.det(a)
print("Det of said array:")
print(result)

Q5. Write a NumPy program to evaluate matrix 3rd power for a below given matrix.
A=[[1 2 3], 
[4 5 6], 
[7 8 9]]

In [0]:
import numpy as np
arr1 = [1, 2, 3]
arr2 = [4, 5, 6]
print("arr1:", arr1)
print("arr2:", arr2)
out = np.power(arr1, arr2)
print("O/P Array", out)

Q6. Write a NumPy program to evaluate Inverse for a below given matrix.
A=[[1 2 3],
[4 5 6],
[7 8 9]]


In [0]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original:")
print(m)
result = np.linalg.inv(m)
print("inv:",result)

Q7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.
[[ 1 2 3 4]
[ 5 6 7 8]
[ 9 10 11 12]
[1 2 3 4]]

In [0]:
import numpy as np
m = np.mat("1 2 3 4; 5 6 7 8; 9 10 11 12; 1 2 3 4")
print("Original:")
print("a/n",m)
w,v=np.linalg.eig(m)
print("Eigen values",w)
print("Eigen values",v)

Q8.Create the following rank 2 array with shape (3, 4)

In [0]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a[0,1])
b[0,0]=77
print(a[0,1])
a.shape

Q9. Write a NumPy program to display all the elements of a given matrix that are bigger than 2;:
[[1 0 3 5] 
[3 6 7 2] 
[3 2 4 1] 
[1 2 0 1]]

In [0]:
import numpy as np
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("original:",x)
print("Values>2", x[x>2])
print("indices are:", np.nonzero(x>2))

Q10. Write a NumPy program to find a matrix or vector norm.

In [0]:
import numpy as np
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector form",result)
m = np.matrix('1, 2; 3, 4')
result1 = np.linalg.norm(m)
print("matrix norm", result1)

Q11. Write a NumPy program to compute the determinant of an array. 
[[2., 1., 1.], 
[1., 2., 1.], 
[1., 1., 2.]]

In [0]:
import numpy as np
a = np.array([[2,1,1],[1,2,1],[1,1,2]])
print("orignal",a)
result = np.linalg.det(a)
print("Determinant is", result)

Q12. Write a NumPy program compute the inverse of a given matrix. 
([[0.1, 0.2], 
[0.3, 0.4], 
[0.5, 0.6], 
[0.7, 0.8]]

In [0]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("original:",a)
result = np.linalg.det(a)
print("determinant is",result)

Q14. Write a NumPy program to add the vector v to each row of the matrix x given below 
x = [[ 2 2 4]
[ 5 5 7]
[ 8 8 10]
[11 11 13]]
v = [1 0 1]


In [0]:
import numpy as np
m = np.array([[2,2,4], [5,5,7],[8,8,10],[11,11,13]])
v=np.array([1,0,1])
print("original vector:",v)
print("original matrix:",m)
print(m)
result=np.empty_like(m)
for i in range(4):
  result[i,:]= m[i,:]+v

print("addition:",result)

Q15. Write a NumPy program compute the sum of the diagonal element of a given array.

In [0]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original Matrix:",m)
result = np.trace(m)
print("Condition number of said matrix:", result)

Q16.Write a program to construct a new set S1 which members are the powers of 2 of 
member of set S={0, 1, 2, 3, 4} 
i.e S1={ 2^0, 2^1, 2^2, 2^3, 2^4}


In [0]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a[0,1])
b[0,0]=77
print(a[0,1])

Q17. Write a NumPy program to get the qr factorization of a given array.

In [0]:
import numpy as np
a = np.array([[4,12,-14], [12,37,-53], [-14,-53,98]], dtype=np.int32)
print("Original Array:")
print(a)
q,r= np.linalg.qr(a)
print("qr factorization of said array is:")
print("q=\n",q,"\nr=\n",r)

Q18. Write a NumPy program to compute the factor of a given array by Singular Value Decomposition.

In [0]:
import numpy as np
a = np.array([[1,0,0,0,2], [0,0,3,0,0], [0,0,0,0,0], [0,2,0,0,0]], dtype=np.int32)
print("Original Aray:")
print(a)
U,s,V = np.linalg.svd(a, full_matrices=False)
q,r= np.linalg.qr(a)
print("Factor of give array by Singular Value Decomposition")
print("U=\n",U,"\ns=\n",s,"\nV=\n",V)

Q19. Write a NumPy program to calculate the L1, L2 and Max norm of a given array. 
A= [-10, 20, 34, 68, -90, 12, 16]

In [0]:
#l1 norm of vector
from numpy import array
from numpy.linalg import norm
a = array([-10,20,34,68,-90,12,16])
print(a)
l1 = norm(a,1)
print(l1)

#l2 norm of vector
from numpy import array
from numpy.linalg import norm
a = array([-10,20,34,68,-90,12,16])
print(a)
l2 = norm(a)
print(l2)

#norm of vector
from numpy import inf
from numpy import array
from numpy.linalg import norm
a = array([-10,20,34,68,-90,12,16])
print(a)
maxnorm = norm(a, inf)
print(maxnorm)

Q20. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product. Go to the editor 
Sample output: 

First array: 
[[ 0.44349753 0.81043761 0.00771825] 
[ 0.64004088 0.86774612 0.19944667] 
[ 0.61520091 0.24796788 0.93798297] 
[ 0.22156999 0.61318856 0.82348994] 
[ 0.91324026 0.13411297 0.00622696]] 

Second array: 
[[ 0.73873542 0.06448186] 
[ 0.90974982 0.06409165] 
[ 0.22321268 0.39147412]] 

Dot product of two arrays: 
[[ 1.06664562 0.08356133] 
[ 1.30677176 0.17496452] 
[ 0.88942914 0.42275803] 
[ 0.90534318 0.37596252] 
[ 0.79804212 0.06992065]]


In [0]:
import numpy as np
x = np.random.random((5,3))
print("First Array:",x)
y=np.random.random((3,2))
print("Second Array",y)
z = np.dot(x, y)
print("Dot Product is:",z)

Q21.Assume that S1 and S2 are the sets with the values S1 = {1, 2, 3, 4} and S2 = {3, 4, 5, 6}. 
Write a program to construct a new set which have the unique members of both the 
sets.

In [0]:
import numpy as np
array1 = np.array([1,2,3,4])
print("Array 1:", array1)
array2 = np.array([3,4,5,6])
print("Array 2:", array2)
print("Unique values in arr1 are:", np.setdiff1d(array1,array2))

Q22.Write a program to do the followingi) Enter a vector u as a n-list.
ii) Enter another vector v as a n-list.
iii) Find the vector au +bv for different values of a and b.
iv) Find the dot produvt of u and v.

In [0]:
import numpy as geek
vect_a = geek.array(([1, 4], [5, 6]))
vect_b = geek.array(([2, 4], [5, 2]))

prod = geek.dot(vect_a, vect_b)
print("Dot Product : \n", prod)

prod = geek.dot(vect_b, vect_a)
print("Dot Product : \n", prod)


Q23.Write a program to do the following-
i) Enter an r by c matrix M(r and c being positive integers). 
ii) Display M in matrix format. 
iii) Display the row and columns of the matrix M. 
iv) Find the scalar multiplication of M for a given scalar. 
v) Find the transpose of the matrix M.

In [0]:
import numpy as np
m = np.array([[1,2], [3,4]])
print("Original Matrix:")
print(m)
result = np.linalg.inv(m)
print("inverse of matrix is:", result)

**Q24**.Write a program to do the following
i) Find the vector-matrix multiplication of a r by c 
matrix M with an c- vector u. 
ii) Find the matrix- matrix product of M with a c 
by p matrix N.

In [0]:
import numpy as np
a = np.array([[5,1,3],
              [1,1,1],
              [1,2,1]])
b = np.array([1,2,3])
print(a*b)

Q25.Write a program to enter a matrix as below and check if it is invertible. If the inverse exists, find the inverse.
[[1 0 3 5]
[3 6 7 2]
[3 2 4 1]
[1 2 0 1]]

In [0]:
import numpy as np
a = np.array([[1,0,3,5], [3,2,4,1], [1,2,0,1], [3, 6, 7, 2]])
ainv = np.linalg.inv(a)
print(ainv)

Q26.Write a program to find:
A. rank, 
B. determinant, 
C. trace, of an array given below.
[[6, 1, 1], 
[4, -2, 5], 
[2, 8, 7]]

In [0]:
#trace of matrix
from numpy import array
from numpy import trace
from numpy.linalg import det
a = array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print(a)
b = trace(a)
print(b)

#determinant of matrix
from numpy import array
from numpy import trace
a = array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print(a)
b = det(a)
print(b)