<a href="https://colab.research.google.com/github/shreyasmalewar/linearalgebra-colab/blob/master/Matrix_Transpose_Inv_Trace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PRACTICAL 6:
Write a program to implement :
1. Transpose
2. Inverse
3. Trace
4. Determinant
5. Rank

#A defined matrix can be transposed, which creates a new matrix with the number of columns
and rows 
ipped. This is denoted by the superscript T next to the matrix AT .
C = AT

In [0]:
# transpose matrix
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# calculate transpose
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


#Inverse
Matrix inversion is a process that nds another matrix that when multiplied with the matrix,
results in an identity matrix. Given a matrix A, nd matrix B, such that AB = In or BA = In.
AB = BA = In

In [0]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


#Trace
A trace of a square matrix is the sum of the values on the main diagonal of the matrix (top-left
to bottom-right).
The trace operator gives the sum of all of the diagonal entries of a matrix
| Page 46, Deep Learning, 2016.
The operation of calculating a trace on a square matrix is described using the notation tr(A)
where A is the square matrix on which the operation is being performed.
tr(A) 
The trace is calculated as the sum of the diagonal values; for example, in the case of a 3 * 3
matrix:
tr(A) = a1;1 + a2;2 + a3;3 (11.7)
Or, using array notation:
tr(A) = A[0; 0] + A[1; 1] + A[2; 2] 
We can calculate the trace of a matrix in NumPy using the trace() function.

In [0]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate trace
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


#Determinant
The determinant of a square matrix is a scalar representation of the volume of the matrix.
The determinant describes the relative geometry of the vectors that make up the
rows of the matrix. More specically, the determinant of a matrix A tells you the
volume of a box with sides given by rows of A.

In [0]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


#Rank
The rank of a matrix is the estimate of the number of linearly independent rows or columns in
a matrix. The rank of a matrix M is often denoted as the function rank().
rank(A) (11.10)
An intuition for rank is to consider it the number of dimensions spanned by all of the vectors
within a matrix. For example, a rank of 0 suggest all vectors span a point, a rank of 1 suggests
all vectors span a line, a rank of 2 suggests all vectors span a two-dimensional plane. The rank
is estimated numerically, often using a matrix decomposition method. A common approach is to
use the Singular-Value Decomposition or SVD for short. NumPy provides the matrix rank()
function for calculating the rank of an array. It uses the SVD method to estimate the rank. The
example below demonstrates calculating the rank of a matrix with scalar values and another
vector with all zero values.

In [0]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [0]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)
# rank 1
M1 = array([
[1,2],
[1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)
# rank 2
M2 = array([
[1,2],
[3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2
