<a href="https://colab.research.google.com/github/shreyasmalewar/linearalgebra-colab/blob/master/Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PRACTICAL 7:
Write a program to implement :
1. Matrix-Matrix Multiplication
2. Matrix-Vector Multiplication
3. Matrix-Scalar Multiplication

#Matrix-Matrix Multiplication
Matrix multiplication, also called the matrix dot product is more complicated than the previous
operations and involves a rule as not all matrices can be multiplied together.
C = A · B (9.15)
or
C = AB (9.16)
The rule for matrix multiplication is as follows:
ˆ The number of columns (n) in the first matrix (A) must equal the number of rows (m) in
the second matrix (B).
For example, matrix A has the dimensions m rows and n columns and matrix B has the
dimensions n and k. The n columns in A and n rows in B are equal. The result is a new matrix
with m rows and k columns.
C(m, k) = A(m, n) · B(n, k) (9.17)
This rule applies for a chain of matrix multiplications where the number of columns in one
matrix in the chain must match the number of rows in the following matrix in the chain.
One of the most important operations involving matrices is multiplication of two
matrices. The matrix product of matrices A and B is a third matrix C. In order for
this product to be defined, A must have the same number of columns as B has rows.
If A is of shape m × n and B is of shape n × p, then C is of shape m × p.


In [0]:
# matrix dot product
from numpy import array
# define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print(B)
# multiply matrices
C = A.dot(B)
print(C)
# multiply matrices with @ operator
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


#Matrix-Vector Multiplication
A matrix and a vector can be multiplied together as long as the rule of matrix multiplication
is observed. Specifically, that the number of columns in the matrix must equal the number of
items in the vector. As with matrix multiplication, the operation can be written using the dot
notation. Because the vector only has one column, the result is always a vector.
c = A · v (9.22)
Or without the dot in a compact form.
c = Av (9.23)
The result is a vector with the same number of rows as the parent matrix.
A =


a1,1 a1,2
a2,1 a2,2
a3,1 a3,2

 (9.24)
v =

v1
v2

(9.25)
c =


a1,1 × v1 + a1,2 × v2
a2,1 × v1 + a2,2 × v2
a3,1 × v1 + a3,2 × v2

 (9.26)
9.7. Matrix-Scalar Multiplicat

In [0]:
# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
B = array([0.5, 0.5])
print(B)
# multiply
C = A.dot(B)
print(C)


[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


#Matrix-Scalar Multiplication
A matrix can be multiplied by a scalar. This can be represented using the dot notation between
the matrix and the scalar.
C = A · b (9.29)
9.7. Matrix-Scalar Multiplication 68
Or without the dot notation.
C = Ab (9.30)
The result is a matrix with the same size as the parent matrix where each element of the
matrix is multiplied by the scalar value.
A =


a1,1 a1,2
a2,1 a2,2
a3,1 a3,2

 (9.31)
C =


a1,1 × b + a1,2 × b
a2,1 × b + a2,2 × b
a3,1 × b + a3,2 × b

 (9.32)
or
C =


a1,1b + a1,2b
a2,1b + a2,2b
a3,1b + a3,2b

 (9.33)
We can also represent this with array notation.
C[0, 0] = A[0, 0] × b
C[1, 0] = A[1, 0] × b
C[2, 0] = A[2, 0] × b
C[0, 1] = A[0, 1] × b
C[1, 1] = A[1, 1] × b
C[2, 1] = A[2, 1] × b
(9.34)
This can be implemented directly in NumPy with the multiplication operator

In [0]:
# matrix-scalar multiplication
from numpy import array
# define matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# define scalar
b = 0.5
print(b)
# multiply
C = A * b
print(C)


[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


1. Eigendecomposition of a Matrix
2. Eigenvectors and Eigenvalues
3. Calculation of Eigendecomposition
4. Confirm an Eigenvector and Eigenvalue
5. Reconstruct Matrix

Eigendecomposition of a Matrix
Eigendecomposition of a matrix is a type of decomposition that involves decomposing a square
matrix into a set of eigenvectors and eigenvalues.
One of the most widely used kinds of matrix decomposition is called eigendecomposition, in which we decompose a matrix into a set of eigenvectors and eigenvalues.

A vector is an eigenvector of a matrix if it satisfies the following equation.
A · v = λ · v 
This is called the eigenvalue equation, where A is the parent square matrix that we are
decomposing, v is the eigenvector of the matrix, and λ is the lowercase Greek letter lambda and
represents the eigenvalue scalar. Or without the dot notation.
Av = λv 

#Eigenvectors and Eigenvalues
Eigenvectors are unit vectors, which means that their length or magnitude is equal to 1.0. They
are often referred as right vectors, which simply means a column vector (as opposed to a row
vector or a left vector). A right-vector is a vector as we understand them. Eigenvalues are
coefficients applied to eigenvectors that give the vectors their length or magnitude. For example,
a negative eigenvalue may reverse the direction of the eigenvector as part of scaling it. A matrix
that has only positive eigenvalues is referred to as a positive definite matrix, whereas if the
eigenvalues are all negative, it is referred to as a negative definite matrix.
Decomposing a matrix in terms of its eigenvalues and its eigenvectors gives valuable
insights into the properties of the matrix. Certain matrix calculations, like computing
the power of the matrix, become much easier when we use the eigendecomposition
of the matrix

#Calculation of Eigendecomposition
An eigendecomposition is calculated on a square matrix using an efficient iterative algorithm, of
which we will not go into the details. Often an eigenvalue is found first, then an eigenvector is
found to solve the equation as a set of coefficients. The eigendecomposition can be calculated in
NumPy using the eig() function. The example below first defines a 3 × 3 square matrix. The
eigendecomposition is calculated on the matrix returning the eigenvalues and eigenvectors.

In [0]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


#Confirm an Eigenvector and Eigenvalue
We can confirm that a vector is indeed an eigenvector of a matrix. We do this by multiplying
the candidate eigenvector by the value vector and comparing the result with the eigenvalue.
First, we will define a matrix, then calculate the eigenvalues and eigenvectors. We will then test
whether the first vector and value are in fact an eigenvalue and eigenvector for the matrix. We
know they are, but it is a good exercise.
The eigenvectors are returned as a matrix with the same dimensions as the parent matrix,
where each column is an eigenvector, e.g. the first eigenvector is vectors[:, 0]. Eigenvalues
are returned as a list, where value indices in the returned array are paired with eigenvectors
by column index, e.g. the first eigenvalue at values[0] is paired with the first eigenvector at
vectors[:, 0].


In [0]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# factorize
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)


[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


#Reconstruct Matrix
We can reverse the process and reconstruct the original matrix given only the eigenvectors and
eigenvalues. First, the list of eigenvectors must be taken together as a matrix, where each vector
becomes a row. The eigenvalues need to be arranged into a diagonal matrix. The NumPy
diag() function can be used for this. Next, we need to calculate the inverse of the eigenvector
matrix, which we can achieve with the inv() NumPy function. Finally, these elements need to
be multiplied together with the dot() function.


In [0]:
# reconstruct matrix
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


#What is the Singular-Value Decomposition
2. Calculate Singular-Value Decomposition
3. Reconstruct Matrix
4. Pseudoinverse
5. Dimensionality Reduction

The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for
reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations
simpler. For the case of simplicity we will focus on the SVD for real-valued matrices and ignore
the case for complex numbers.
A = U · Σ · V
T
(16.1)
Where A is the real n × m matrix that we wish to decompose, U is an m × m matrix, Σ
represented by the uppercase Greek letter sigma) is an m × n diagonal matrix, and V
T
is the V
transpose of an n × n matrix where T is a superscript.
The Singular Value Decomposition is a highlight of linear algebra.
— Page 371, Introduction to Linear Algebra, 2016.
The diagonal values in the Σ matrix are known as the singular values of the original matrix
A. The columns of the U matrix are called the left-singular vectors of A, and the columns
of V are called the right-singular vectors of A. The SVD is calculated via iterative numerical
methods. We will not go into the details of these methods. Every rectangular matrix has a
singular value decomposition, although the resulting matrices may contain complex numbers
and the limitations of floating point arithmetic may cause some matrices to fail to decompose
neatly.

#Calculate Singular-Value Decomposition
The SVD can be calculated by calling the svd() function. The function takes a matrix and
returns the U, Σ and V
T
elements. The Σ diagonal matrix is returned as a vector of singular
values. The V matrix is returned in a transposed form, e.g. V
T
. The example below defines a
3 × 2 matrix and calculates the singular-value decomposition.

In [0]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [0]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
