<a href="https://colab.research.google.com/github/shreyasmalewar/linearalgebra-colab/blob/master/Matrix-Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PRACTICAL 5:
Write a program to implement :
1. Square Matrix
2. Symmetric Matrix
3. Triangular Matrix
4. Diagonal Matrix
5. Identity Matrix
6. Orthogonal Matrix


#Square Matrix
A square matrix is a matrix where the number of rows (n) is equivalent to the number of
columns (m).
n  m (10.1)
The square matrix is contrasted with the rectangular matrix where the number of rows and
columns are not equal. Given that the number of rows and columns match, the dimensions are
usually denoted as n, e.g. nn. The size of the matrix is called the order, so an order 4 square
matrix is 4  4. The vector of values along the diagonal of the matrix from the top left to the
bottom right is called the main diagonal. Below is an example of an order 3 square matrix.
M =(1 2 3;1 2 3;1 2 3)

Square matrices are readily added and multiplied together and are the basis of many simple
linear transformations, such as rotations (as in the rotations of images).

#Symmetric Matrix
A symmetric matrix is a type of square matrix where the top-right triangle is the same as the
bottom-left triangle.
It is no exaggeration to say that symmetric matrices S are the most important
matrices the world will ever see | in the theory of linear algebra and also in the
applications.
| Page 338, Introduction to Linear Algebra, Fifth Edition, 2016.
To be symmetric, the axis of symmetry is always the main diagonal of the matrix, from the
top left to the bottom right. Below is an example of a 5  5 symmetric matrix.
M =(
1 2 3 4 5;
2 1 2 3 4;
3 2 1 2 3;
4 3 2 1 2;
5 4 3 2 1;
)
A symmetric matrix is always square and equal to its own transpose. The transpose is an
operation that 
ips the number of rows and columns. It is explained in more detail in the next
lesson.
M = MT

#Triangular Matrix
A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left
of the matrix with the remaining elements lled with zero values. A triangular matrix with
values only above the main diagonal is called an upper triangular matrix. Whereas, a triangular
matrix with values only below the main diagonal is called a lower triangular matrix. Below is
an example of a 3  3 upper triangular matrix.
M =
[
1 2 3;
0 2 3;
0 0 3;
]
Below is an example of a 3  3 lower triangular matrix.
M =[
1 0 0;
1 2 0;
1 2 3]
A (10.6)
NumPy provides functions to calculate a triangular matrix from an existing square matrix.
The tril() function to calculate the lower triangular matrix from a given matrix and the
triu() to calculate the upper triangular matrix from a given matrix The example below denes
a 3  3 square matrix and calculates the lower and upper triangular matrix from it.

In [0]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# lower triangular matrix
lower = tril(M)
print(lower)
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


#Diagonal Matrix
A diagonal matrix is one where values outside of the main diagonal have a zero value, where the
main diagonal is taken from the top left of the matrix to the bottom right. A diagonal matrix
is often denoted with the variable D and may be represented as a full matrix or as a vector of
values on the main diagonal.
Diagonal matrices consist mostly of zeros and have non-zero entries only along the
main diagonal.

In [0]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


#Identity Matrix
An identity matrix is a square matrix that does not change a vector when multiplied. The
values of an identity matrix are known. All of the scalar values along the main diagonal (top-left
to bottom-right) have the value one, while all other values are zero.
An identity matrix is a matrix that does not change any vector when we multiply
that vector by that matrix.

In [0]:
# identity matrix
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#Orthogonal Matrix
Two vectors are orthogonal when their dot product equals zero. The length of each vector is 1
then the vectors are called orthonormal because they are both orthogonal and normalized.

In [0]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
[1, 0],
[0, -1]])
print(Q)
# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]
