<a href="https://colab.research.google.com/github/shreyasmalewar/linearalgebra-colab/blob/master/Numpy-Functions-Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##Write a program to implement :
1. NumPy N-dimensional Array
2. Functions to Create Arrays
3. Combining Arrays

##NumPy N Dimensional Array
NumPy is a Python library that can be used for scientic and numerical applications and is the
tool to use for linear algebra operations. The main data structure in NumPy is the ndarray,
which is a shorthand name for N-dimensional array. When working with NumPy, data in an
ndarray is simply referred to as an array. It is a xed-sized array in memory that contains data
of the same type, such as integers or 
oating point values.
The data type supported by an array can be accessed via the dtype attribute on the array.
The dimensions of an array can be accessed via the shape attribute that returns a tuple
describing the length of each dimension. There are a host of other attributes. A simple way to create an array from data or simple Python data structures like a list is to use the array()
function. The example below creates a Python list of 3 
Floating point values, then creates an
ndarray from the list and access the arrays' shape and data type.

In [0]:
#import Numpy
from numpy import array
#create Array
a=[5.6,9.6,3.9]
a=array(a)
#print a
print(a)
#print shape
print(a.shape)
#print datatype
print(a.dtype)

[5.6 9.6 3.9]
(3,)
float64


## Create Array

###Empty
The empty() function will create a new array of the specied shape. The argument to the
function is an array or tuple that species the length of each dimension of the array to create.
The values or content of the created array will be random and will need to be assigned before
use. The example below creates an empty 3  3 two-dimensional array.

In [0]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)
print(a.dtype)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]
float64


###Ones
The ones() function will create a new array of the specied size with the contents lled with
one values. The argument to the function is an array or tuple that species the length of each
dimension of the array to create. The example below creates a 5-element one-dimensional array.

In [0]:
#create array
from numpy import ones
from numpy import array
a=ones([3,3])
print(a)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


###Zeros
The zeros() function will create a new array of the specied size with the contents lled with
zero values. The argument to the function is an array or tuple that species the length of each
dimension of the array to create. The example below creates a 3  5 zero two-dimensional array.

In [0]:
# create empty array
from numpy import zeros
a = zeros([3,3])
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


##Stacking

###Vertical Stack
Given two or more existing arrays, you can stack them vertically using the vstack() function.
For example, given two one-dimensional arrays, you can create a new two-dimensional array
with two rows by vertically stacking them. This is demonstrated in the example below.

In [0]:
#import library
from numpy import array
from numpy import vstack
import numpy as np
#create array 1
a1=[1,2,3]
#create array 2
a2=[4,5,6]
print(a1)
print(a2)
print(np.vstack((a1,a2)))


[1, 2, 3]
[4, 5, 6]
[[1 2 3]
 [4 5 6]]


###Horizontal Stack
Given two or more existing arrays, you can stack them horizontally using the hstack() function.
For example, given two one-dimensional arrays, you can create a new one-dimensional array or
one row with the columns of the rst and second arrays concatenated. This is demonstrated in
the example below.

In [0]:
#import library
from numpy import array
from numpy import hstack
import numpy as np
#create array 1
a1=[1,2,3]
#create array 2
a2=[4,5,6]
print(a1)
print(a2)
print(np.hstack((a1,a2)))


[1, 2, 3]
[4, 5, 6]
[1 2 3 4 5 6]
