<a href="https://colab.research.google.com/github/shreyasmalewar/linearalgebra-colab/blob/master/Vector_Arith_Dot_Scalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##Write a program to implement :

1. Vector Arithmetic
2. Vector Dot Product
3. Vector-Scalar Multiplication

#Defining a vector
We can represent a vector in Python as a NumPy array. A NumPy array can be created from a list of numbers. For example, below we define a vector with the length of 3 and the integer values 1, 2 and 3.

In [0]:
from numpy import array
v=([1,2,3])
print(v)

[1, 2, 3]


#Vector Arithmentic 
In this section will demonstrate simple vector-vector arithmetic, where all operations are performed element-wise between two vectors of equal length to result in a new vector with the same length

#Vector Addition
Two vectors of equal length can be added together to create a new third vector. c = a + b (7.3) The new vector has the same length as the other two vectors. Each element of the new vector is calculated as the addition of the elements of the other vectors at the same index; for example: c = (a1 + b1; a2 + b2; a3 + b3)

In [0]:
from numpy import array
a=array([1,2,3])
print(a)
b=array([4,5,6])
print(b)
c=a+b
print(c)

[1 2 3]
[4 5 6]
[5 7 9]


#Vector Subtraction 
One vector can be subtracted from another vector of equal length to create a new third vector. c = a - b (7.6) 7.4. Vector Arithmetic 47 As with addition, the new vector has the same length as the parent vectors and each element of the new vector is calculated as the subtraction of the elements at the same indices. c = (a1 - b1; a2 - b2; a3 - b3)

In [0]:
from numpy import array
a=array([1,2,3])
print(a)
b=array([0.5,0.5,0.5])
print(b)
c=a-b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


#Vector Multiplication
Two vectors of equal length can be multiplied together. c = a * b (7.9) As with addition and subtraction, this operation is performed element-wise to result in a new vector of the same length. c = (a1* b1; a2 * b2; a3 * b3) or c = (a1b1; a2b2; a3b3)

In [0]:
from numpy import array
a=array([1,2,3])
print(a)
b=array([3,4,5])
print(b)
c=a*b
print(c)

[1 2 3]
[3 4 5]
[ 3  8 15]


#Vector Division
Two vectors of equal length can be divided. c =a/b

As with other arithmetic operations, this operation is performed element-wise to result in a new vector of the same length. c = (a1/b1;a2/b2;a3/b3)

In [0]:
from numpy import array
a=array([12,15,20])
print(a)
b=array([4,3,4])
print(b)
c=a/b
print(c)

[12 15 20]
[4 3 4]
[3. 5. 5.]


#Vector Dot Product
We can calculate the sum of the multiplied elements of two vectors of the same length to give a scalar. This is called the dot product, named because of the dot operator used when describing the operation. The dot product is the key tool for calculating vector projections, vector decompositions, and determining orthogonality. The name dot product comes from the symbol used to denote it

In [0]:
from numpy import array
a=array([1,2,3])
print(a)
b=array([1,2,3])
print(b)
c=a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


#Vector Scalar Multiplication
A vector can be multiplied by a scalar, in eect scaling the magnitude of the vector. To keep notation simple, we will use lowercase s to represent the scalar value. c = s * v (7.19) or c = sv (7.20) The multiplication is performed on each element of the vector to result in a new scaled vector of the same length. c = (s * v1; s * v2; s * v3)

In [0]:
from numpy import array
a=array([1,2,3])
print(a)
s=0.5
print(s)
c=s*a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]
