<a href="https://colab.research.google.com/github/shreyasmalewar/linearalgebra-colab/blob/master/Vector_Norm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PRACTICAL 4:
Write a program to implement :

1. Vector Norm
2. Vector L1 Norm
3. Vector L2 Norm
4. Vector Max Norm

#Vector Norm
Calculating the size or length of a vector is often required either directly or as part of a broader vector or vector-matrix operation. The length of the vector is referred to as the vector norm or the vector's magnitude. The length of a vector is a nonnegative number that describes the extent of the vector in space, and is sometimes referred to as the vector's magnitude or the norm.The length of the vector is always a positive number, except for a vector of all zero values. It is calculated using some measure that summarizes the distance of the vector from the origin of the vector space. For example, the origin of a vector space for a vector with 3 elements is (0; 0; 0). Notations are used to represent the vector norm in broader calculations and the type of vector norm calculation almost always has its own unique notation. We will take a look at a few common vector norm calculations used in machine learning.

#Vector L1 Norm
The length of a vector can be calculated using the L1 norm, where the 1 is a superscript of the L. The notation for the L1 norm of a vector is jjvjj1, where 1 is a subscript. As such, this length is sometimes called the taxicab norm or the Manhattan norm. L1(v) = ||v||1 The L1 norm is calculated as the sum of the absolute vector values, where the absolute value of a scalar uses the notation ja1j. In eect, the norm is a calculation of the Manhattan distance from the origin of the vector space. ||v||1 = |a1| + |a2| + |a3| In several machine learning applications, it is important to discriminate between elements that are exactly zero and elements that are small but nonzero. In these cases, we turn to a function that grows at the same rate in all locations, but retains mathematical simplicity: the L1 norm.

In [0]:
from numpy import array
from numpy. linalg import norm
a=array([1,2,3])
print(a)
l1=norm(a,1)
print(l1)

[1 2 3]
6.0


#Vector L2 Norm
The length of a vector can be calculated using the L2 norm, where the 2 is a superscript of the L. The notation for the L2 norm of a vector is jjvjj2 where 2 is a subscript. L2(v) = ||v||2 The L2 norm calculates the distance of the vector coordinate from the origin of the vector space. As such, it is also known as the Euclidean norm as it is calculated as the Euclidean distance from the origin. The result is a positive distance value. The L2 norm is calculated as the square root of the sum of the squared vector values. ||v||2 =sqrt(a12+a22+a3**2) The L2 norm of a vector can be calculated in NumPy using the norm() function with default parameters.



In [0]:
from numpy import array
from numpy. linalg import norm
a=array([1,2,3])
print(a)
l2=norm(a,2)
print(l2)


[1 2 3]
3.7416573867739413


#Vector Max Norm
The length of a vector can be calculated using the maximum norm, also called max norm. Max norm of a vector is referred to as Linf where inf is a superscript and can be represented with the infinity symbol. The notation for max norm is jjvjjinf , where inf is a subscript. Linf (v) = ||v||inf The max norm is calculated as returning the maximum value of the vector, hence the name. ||v||inf = max a1; a2; a3 The max norm of a vector can be calculated in NumPy using the norm() function with the order parameter set to inf.

In [0]:
from math import inf
from numpy import array
from numpy. linalg import norm
a=array([1,2,3])
print(a)
maxnorm=norm(a,inf)
print(maxnorm)


[1 2 3]
3.0


#Let x=[-10,2,4,8,9] then which of this is greater L1,L2,L3,Linf

In [0]:
from math import inf
from numpy import array
from numpy. linalg import norm
a=array([-10,2,4,8,9])
print(a)
l1=norm(a,1)
l2=norm(a,2)
l3=norm(a,3)
maxnorm=norm(a,inf)
print(l1)
print(l2)
print(l3)
print(maxnorm)


[-10   2   4   8   9]
33.0
16.278820596099706
13.224884189174803
10.0
